#!/bin/bash
# clear-browser-cache.sh - Instrucciones para limpiar caché del navegador

echo "======================================================================"
echo "  OWFINANCE - Limpieza de Caché del Navegador"
echo "======================================================================"
echo ""
echo "Este script proporciona instrucciones para limpiar el caché en"
echo "diferentes navegadores después de un deployment."
echo ""
echo "----------------------------------------------------------------------"
echo "  OPCIÓN 1: Cache Busting Automático (RECOMENDADO para Producción)"
echo "----------------------------------------------------------------------"
echo ""
echo "1. Activar versionHash en quasar.config.ts:"
echo ""
echo "   build: {"
echo "     versionHash: true,  // <-- Agregar esto"
echo "   }"
echo ""
echo "2. Deploy con timestamp en query string:"
echo ""
echo "   TIMESTAMP=\$(date +%s)"
echo "   echo \"Usuarios deben visitar: https://appfinanzas.blockshift.website/app/?v=\$TIMESTAMP\""
echo ""
echo "----------------------------------------------------------------------"
echo "  OPCIÓN 2: Hard Reload Manual (para Testing/DEV)"
echo "----------------------------------------------------------------------"
echo ""
echo "Chrome/Edge/Brave:"
echo "  • Mac: Cmd + Shift + R"
echo "  • Windows/Linux: Ctrl + Shift + R"
echo ""
echo "Firefox:"
echo "  • Mac: Cmd + Shift + R"
echo "  • Windows/Linux: Ctrl + F5"
echo ""
echo "Safari:"
echo "  • Mac: Cmd + Option + R"
echo ""
echo "Mobile (Chrome Android):"
echo "  • Menú → Configuración → Privacidad → Borrar datos de navegación"
echo "  • Seleccionar \"Imágenes y archivos en caché\""
echo ""
echo "Mobile (Safari iOS):"
echo "  • Ajustes → Safari → Borrar historial y datos de sitios web"
echo ""
echo "----------------------------------------------------------------------"
echo "  OPCIÓN 3: Service Worker Clear (PWA/Capacitor)"
echo "----------------------------------------------------------------------"
echo ""
echo "Si la app usa Service Workers (Capacitor mobile):"
echo ""
echo "1. Abrir DevTools en Chrome"
echo "2. Application → Service Workers"
echo "3. Click \"Unregister\" en el SW activo"
echo "4. Application → Storage → Clear site data"
echo ""
echo "----------------------------------------------------------------------"
echo "  OPCIÓN 4: Versión URL (Deployment Notification)"
echo "----------------------------------------------------------------------"
echo ""
echo "Enviar notificación a usuarios con link versionado:"
echo ""
echo "  https://appfinanzas.blockshift.website/app/?v=1733832500"
echo "  https://appfinanzasdev.blockshift.website/app/?nocache=\$(date +%s)"
echo ""
echo "----------------------------------------------------------------------"
echo "  OPCIÓN 5: Meta Tags Cache Control (HTML)"
echo "----------------------------------------------------------------------"
echo ""
echo "Agregar en index.html:"
echo ""
echo '  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">'
echo '  <meta http-equiv="Pragma" content="no-cache">'
echo '  <meta http-equiv="Expires" content="0">'
echo ""
echo "----------------------------------------------------------------------"
echo "  VERIFICACIÓN POST-LIMPIEZA"
echo "----------------------------------------------------------------------"
echo ""
echo "1. Abrir DevTools (F12)"
echo "2. Network tab → Disable cache checkbox"
echo "3. Recargar página"
echo "4. Verificar que assets JavaScript tienen hash nuevo:"
echo ""
echo "   ✅ LiteMobileLayout.abc123.js  (nuevo hash)"
echo "   ❌ LiteMobileLayout.xyz789.js  (hash viejo)"
echo ""
echo "5. Verificar rutas en consola:"
echo ""
echo "   console.log('Routes:', { home: '/user/home', ... })"
echo ""
echo "======================================================================"
echo ""
echo "Para más info: docs/DEPLOYMENT-STRATEGY.md"
echo ""
